url: 'http://theoctopod.github.io/essential-programs/'
exclude:
    - 'src/'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'contributors.md'
    - 'preface.md'
    - 'program-list.md'
    - 'website-list.md'
defaults:
    -
        values:
            layout: "default"
