url: 'http://theoctopod.github.io/essential-programs/'
exclude:
    - 'src/'
    - 'Gemfile'
    - 'Gemfile.lock'
sass:
    sass_dir: css
defaults:
    -
        values:
            layout: "default"
